export const PROMISE_MIDDLEWARE_SUFFIX = {
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    FULFILLED: 'FULFILLED',
}
export const ACTION_TYPES = {
    FETCH_STOCK_PRICES: 'FETCH_STOCK_PRICES',
    UPDATE_STOCK_PRICE: 'UPDATE_STOCK_PRICE',
    DELETE_STOCK_PRICE: 'DELETE_STOCK_PRICE',
    INIT: 'INIT',
}